language: node_js

node_js:
  - "10"

notifications:
  email: false

cache:
  directories:
    - "node_modules"

script:
  - yarn test
  - yarn build
  - echo my-custom-domain.ru > public/CNAME

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  committer-from-gh: true
  skip-cleanup: true
  keep-history: true
  local-dir: public
  repo: anyakul/big-trip
  target-branch: master
  on:
    branch: master
